### ISSUE TITLE
How to download this as addon for Firefox?

### ISSUE THREAD

**Issue by Smultie** [alxwrd/open-with-pennywise#1]
See subject.

**Comment by alxwrd** [comment]
Hi @Smultie, I haven't released this for Firefox add-ons yet as I was waiting on kamranahmedse/pennywise#90. But now that's been merged, I'll look to release tomorrow.

I'll update here once that's done.

**Comment by Smultie** [comment]
Cheers! Thanks a lot!

**Comment by alxwrd** [comment]
Hi @Smultie! The Firefox version has been published and is available here: https://addons.mozilla.org/en-GB/firefox/addon/open-with-pennywise/.
