### ISSUE TITLE
No 'Pennywise' in right click menu

### ISSUE THREAD

**Issue by Smultie** [alxwrd/open-with-pennywise#2]
Hi, running the latest version of the addon, latest version of Pennywise and Firefox Beta (latest).
I don't see 'open in Pennywise' anywhere, nor anything I can set in the add-on config...
Am I missing something?

**Comment by alxwrd** [comment]
Ah, I've just realised PR 90 for pennywise hasn't been released yet. It's on the master branch but it hasn't been built and added to the release page.

You'll either have to build pennywise from source, or ask on the pennywise repo for a release. If you need help building from source, let me know.

**Comment by Smultie** [comment]
Thanks for the quick reply!
I'll just wait for the new Pennywise release, thanks!

**Comment by rrevanth** [comment]
@alxwrd Hey, can you point me to the build instructions for mac. I really like pennywise and would love to have the borderless feature you implemented.

**Comment by alxwrd** [comment]
@rrevanth  thank you 😊 

Just to confirm you're using Google Chrome Canary (the dev nightly build) on Mac?

I've currently only tested on Google Chrome stable on Windows. But I will look to see if it's a Canary issue (I don't have access to a Mac).

**Comment by alxwrd** [comment]
I've just tried with Google Chrome Canary, and it seems to be working ok.

With Pennywise running (built with PR#90), if you go to http://localhost:6280/?url=www.google.com does Pennywise navigate to Google?

![gif](https://user-images.githubusercontent.com/13941027/50632646-7c585c80-0f40-11e9-8214-7cb97e683f8a.gif)

**Comment by alxwrd** [comment]
Do you have pennywise running when you try?

**Comment by rrevanth** [comment]
This site can’t be reached.
localhost refused to connect.

I even cleared out /etc/hosts file. I'm not sure about any fix problem.

**Comment by alxwrd** [comment]
Just be aware that the changes to pennywise that make this extension work have been merged into master, but haven't yet been labelled for release. The changes are for a frameless window are also in an un-merged PR. If you built from source from the frameless PR, it won't have the remote control functionality.

**Comment by alxwrd** [comment]
I've just rebased my `borderless-window` branch onto `master` for Pennywise.

So if you want both borderless windows and remote control features you can:

```shell
git clone https://github.com/alxwrd/pennywise.git
git checkout borderless-window
yarn install   # npm install
yarn build
```

Atleast until this makes it into a released version of Pennywise.

**Comment by rrevanth** [comment]
With pennywise running, if you go to http://localhost:6280/?url={url}. Pennywise is opening the url but I can't see pennywise in browser context menu and if I click the icon, it's opening the github project.

I wonder if extension has to request access to browser url?

**Comment by alxwrd** [comment]
@rrevanth, yes the extension should request access to `localhost:6280`.

The extension sends a request every few minutes  to `localhost:6280` to see if pennywise is running. If it is, the context menu option will appear when right clicking on a link.

I can look at adding an options page to toggle the 'polling' behaviour so the pennywise option is always available.

**Comment by rrevanth** [comment]
@alxwrd  Hey, I got the new version installed. Thanks for the detailed instructions.

As for the option, I think it's good to have the option always on like fenetre and open the site on one click of the icon in the toolbar. It's just a suggestion though! what you are helping is really awesome!

**Comment by kamranahmedse** [comment]
@alxwrd thank you for your work on this. I have released the new build - you may update the readme.

**Comment by alxwrd** [comment]
@kamranahmedse excellent, thank you! 🎉
